baseurl = "https://bilaldurrani.io"
languageCode = "en-us"
title = "Bilal Durrani"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
disableLiveReload = true

# code highlighting
pygmentsUseClassic=true
pygmentsCodeFences = true
PygmentsStyle = "friendly" 

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/post"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
    
# [[menu.main]]
#     name = "Categories"
#     url = "/categories/"
#     weight = 3
# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = 4

[params]
    description = "A website built using Hugo"
    footer = "&copy; Bilal Durrani 2020 | [Github](https://github.com/bdurrani)"  
